openapi: "3.0.0"
info:
  title: "flop-gen api"
  description: "REST API for interfacing flop-gen api and engine"
  version: "1.0.0"
  contact:
    name: "Arib Dhuka"
    email: "atxarib99@gmail.com"

servers:
  - url: "http://localhost:3001/flop-gen/v1"

components:
  schemas:
    Filter:
      type: object
      required:
      - name
      properties:
        name:
          type: string
        description:
          type: string
        options:
          type: array
          items:
            type: string
    GenerateRequest:
      type: object
      properties:
        filters:
          type: array
          items:
            $ref: '#/components/schemas/Filter'

  requestBodies:
    GenerateRequest:
      description: 'Engine parameters'
      required: true
      content:
        application/json:
          schema:
            x-body-name: 'generateRequest'
            $ref: '#/components/schemas/GenerateRequest'


paths:
  /greeting/{name}:
    post:
      operationId: app.post_greeting
      responses:
        '200':
          description: 'test'
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string

  /filters:
    get:
      operationId: app.get_filters
      description: "returns all filter info"
      responses:
        "200":
          description: "All available filters"
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Filter'
  /generate:
    post:
      operationId: app.generate
      description: "generate flops based on request body parameters"
      requestBody:
        content:
          application/json:
            schema: 
              $ref: '#/components/requestBodies/GenerateRequest'
      responses:
        "200":
          description: "Engine output"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  
