openapi: "3.0.0"
info:
  title: "flop-gen api"
  description: "REST API for interfacing flop-gen api and engine"
  version: "1.0.0"
  contact:
    name: "Arib Dhuka"
    email: "atxarib99@gmail.com"

servers:
  - url: "http://localhost:3001/flop-gen/v1"

components:
  schemas:
    Filter:
      type: object
      required:
      - name
      properties:
        name:
          type: string
        description:
          type: string
        options:
          type: array
          items:
            type: string
    GenerateRequest:
      type: object
      properties:
        filters:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              selection:
                type: string
        engine:
          type: object
          properties:
            flops:
              type: integer
              default: 100
            weights:
              type: boolean
              default: false

  requestBodies:
    GenerateRequest:
      description: 'Engine parameters'
      required: true
      content:
        application/json:
          schema:
            x-body-name: 'generateRequest'
            $ref: '#/components/schemas/GenerateRequest'


paths:
  /filters:
    get:
      operationId: app.get_filters
      description: "returns all filter info"
      tags: 
        - filters
      responses:
        "200":
          description: "All available filters"
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/Filter'

  /filters/{name}:
    get:
      operationId: app.get_filter
      description: "return a specific filters info"
      tags:
        - filters
      parameters:
        - in: path
          name: name
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Filter info"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Filter'

  /generate:
    post:
      operationId: service.engine.generate
      description: "generate flops based on request body parameters"
      tags:
        - engine
      requestBody:
        $ref: '#/components/requestBodies/GenerateRequest'
      responses:
        "200":
          description: "Engine output"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  example: AsKhQc

tags:
  - name: filters
    description: "Information about filters"
  - name: engine
    description: "Engine communication and operations"

  
